### ISSUE TITLE
Incompatibility with Canvas Export and Webpage Export Plugin

### ISSUE THREAD

**Issue by Aeases** [Akifyss/obsidian-border#66] opened 2023-04-26 10:07 UTC
For some reason if I try and export a full canvas image or export using the [Webpage Export Plugin](https://github.com/KosmosisDire/obsidian-webpage-export) while using the border theme it doesn't export correctly. I'm using a sandbox vault in all the images, and have installer version 1.1.9
![image](https://user-images.githubusercontent.com/96164686/234541485-888a51f4-0574-44e5-a316-663ce9d12512.png)
# Canvas
The **full page** canvas export does not render correctly and seems to random other aspects of obsidian, the viewport export works fine however.
<details>
<summary>
Canvas pre-export 
</summary>

>![image](https://user-images.githubusercontent.com/96164686/234538160-9db83446-a869-4fa5-92b0-6c4a91421564.png)
</details>

<details>
<summary>
Canvas post-export 
</summary>

>![CanvasBorder](https://user-images.githubusercontent.com/96164686/234538515-392c47f7-f7be-4689-ac2a-1fdccc40a771.png)
</details>

# [Webpage Export Plugin](https://github.com/KosmosisDire/obsidian-webpage-export)
The theme completely breaks exporting, you end up with just a little bit of text and no content, the content itself does appear in the html 'code' still however, it doesn't render.
<details>
<summary>
Note pre-export 
</summary>

![image](https://user-images.githubusercontent.com/96164686/234540333-d3d05fed-7dd2-4612-bb13-8bb2a6bf507f.png)
</details>

<details>
<summary>
Note post-export 
</summary>

![image](https://user-images.githubusercontent.com/96164686/234540803-ae4eb02d-4aed-47b2-a947-a0b0e434b631.png)
</details>

**Comment by Akifyss** [comment] 2023-04-26 13:42
The first issue has been resolved in the latest version.
The cause of the second issue may be due to the use of SVG images in border theme. I am unlikely to remove all the SVGs used in the theme because of this plugin. Therefore, submitting an issue to the plugin repo may be more helpful.

**Closed by Akifyss** 2023-04-26 13:42 UTC

**Comment by Manukineko** [comment] 2024-11-29 00:27
> The first issue has been resolved in the latest version. The cause of the second issue may be due to the use of SVG images in border theme. I am unlikely to remove all the SVGs used in the theme because of this plugin. Therefore, submitting an issue to the plugin repo may be more helpful.

Well.
I have the same issue and :
[https://github.com/KosmosisDire/obsidian-webpage-export/issues/65#issuecomment-1575060573](https://github.com/KosmosisDire/obsidian-webpage-export/issues/65#issuecomment-1575060573)

Let the ping-pong play begins XD
